version: '2'
services:
  
  php-apache:
    build:
      context: ./
      dockerfile: Dockerfile
    image: tvalero/docker-php-5.3-apache
    restart: always


networks:
  default:
     driver: bridge 
