version: '2'
services:
  
  php-apache:
    build:
      context: ./
      dockerfile: Dockerfile
    image: quay.io/mivegec/docker-php-5.3-apache:DEV-2018-12-14
    restart: always


networks:
  default:
     driver: bridge 
